# ML/Clustering/models/dbscan_family.py

from __future__ import annotations

from typing import Optional

import numpy as np

from sklearn.cluster import DBSCAN
from sklearn.cluster import OPTICS

import hdbscan

from .density import BaseDensityCluster


# =====================================================
# DBSCAN
# =====================================================

class DBSCANCluster(BaseDensityCluster):
    """
    Density-Based Spatial Clustering of Applications
    with Noise.
    """

    def __init__(
        self,
        eps: float = 0.5,
        min_samples: int = 5,
        metric: str = "euclidean"
    ):

        super().__init__()

        if eps <= 0:
            raise ValueError(
                "eps must be greater than 0."
            )

        if min_samples < 2:
            raise ValueError(
                "min_samples must be >= 2."
            )

        self.eps = eps
        self.min_samples = min_samples
        self.metric = metric

        self.n_features_ = None

    def fit(
        self,
        X
    ):

        X = np.asarray(X)

        self.n_features_ = X.shape[1]

        self.model = DBSCAN(
            eps=self.eps,
            min_samples=self.min_samples,
            metric=self.metric
        )

        self.labels_ = self.model.fit_predict(X)

        return self


# =====================================================
# OPTICS
# =====================================================

class OPTICSCluster(BaseDensityCluster):
    """
    Ordering Points To Identify Clustering Structure.
    """

    def __init__(
        self,
        min_samples: int = 5,
        max_eps: float = np.inf,
        metric: str = "euclidean"
    ):

        super().__init__()

        if min_samples < 2:
            raise ValueError(
                "min_samples must be >= 2."
            )

        self.min_samples = min_samples
        self.max_eps = max_eps
        self.metric = metric

        self.n_features_ = None

    def fit(
        self,
        X
    ):

        X = np.asarray(X)

        self.n_features_ = X.shape[1]

        self.model = OPTICS(
            min_samples=self.min_samples,
            max_eps=self.max_eps,
            metric=self.metric
        )

        self.labels_ = self.model.fit_predict(X)

        return self

    @property
    def reachability(self):
        """
        Reachability distance of each sample.
        """

        if self.model is None:
            return None

        return self.model.reachability_

    @property
    def ordering(self):
        """
        Ordering generated by OPTICS.
        """

        if self.model is None:
            return None

        return self.model.ordering_

    @property
    def core_distances(self):
        """
        Core distance of each observation.
        """

        if self.model is None:
            return None

        return self.model.core_distances_


# =====================================================
# HDBSCAN
# =====================================================

class HDBSCANCluster(BaseDensityCluster):
    """
    Hierarchical Density-Based Spatial Clustering.
    """

    def __init__(
        self,
        min_cluster_size: int = 5,
        min_samples: Optional[int] = None,
        metric: str = "euclidean"
    ):

        super().__init__()

        if min_cluster_size < 2:
            raise ValueError(
                "min_cluster_size must be >= 2."
            )

        self.min_cluster_size = min_cluster_size
        self.min_samples = min_samples
        self.metric = metric

        self.n_features_ = None

        self.probabilities_ = None

    def fit(
        self,
        X
    ):

        X = np.asarray(X)

        self.n_features_ = X.shape[1]

        self.model = hdbscan.HDBSCAN(
            min_cluster_size=self.min_cluster_size,
            min_samples=self.min_samples,
            metric=self.metric
        )

        self.labels_ = self.model.fit_predict(X)

        self.probabilities_ = (
            self.model.probabilities_
        )

        return self

    @property
    def cluster_probabilities(self):
        """
        Membership probability of each sample.
        """

        return self.probabilities_

    @property
    def outlier_scores(self):
        """
        Outlier score per observation.
        Higher = more anomalous.
        """

        if self.model is None:
            return None

        return self.model.outlier_scores_

    @property
    def cluster_persistence(self):
        """
        Stability score of discovered clusters.

        Higher values indicate
        more persistent clusters.
        """

        if self.model is None:
            return None

        return self.model.cluster_persistence_


# =====================================================
# EXPORTS
# =====================================================

__all__ = [
    "DBSCANCluster",
    "OPTICSCluster",
    "HDBSCANCluster"
]